name = "lgt-mysite"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "pnpm run build"

# Environment variables can be defined here
[vars]
# Add your environment variables here
# API_URL = "https://api.example.com"

# Define development environment
[env.development]
name = "lgt-mysite-dev"

# Define production environment
[env.production]
name = "lgt-mysite"

# Optional: Configure custom domains
# [[routes]]
# pattern = "example.com/*"
# zone_name = "example.com"